### ISSUE TITLE
Input using rds file downloaded from GEO

### ISSUE THREAD

**Issue by xliao8** [stergiostsartsalis/vascular_AD#1]
Thank you so much for putting your incredible work together for sharing! I was wondering have integration, normalization, and dimensional reduction been performed using LIGER for the rds files included within GSE252921 repository? What's the input datasets for the Basic_Analysis file? Thanks for taking time answering my question!

**Comment by stergiostsartsalis** [comment]
Hi, the GSE252921 contains only a part of the datasets that we used in this paper, in which Seurat was used for these steps. The Basic_Analysis file mainly refers to the other two datasets (Smith et al, https://link.springer.com/article/10.1007/s00401-021-02372-6 and Gerrits et al, https://link.springer.com/article/10.1007/s00401-021-02263-w) in which processing was done with the scFlow pipeline (https://nf-co.re/scflow/dev/) with default parameters, which indeed employs Liger for integration. The output of this pipeline is basically a SingleCellExperiment object, which was easily transformed into a Seurat object. For more details and if you need more specific scripts, please don't hesitate to contact me directly!
